[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"

[compat]
BenchmarkTools = "1"
ReferenceFrameRotations = "3.2"
julia = "1.10"

[sources]
ReferenceFrameRotations = {path = ".."}
